### ISSUE TITLE
team-106-the-kingsnakes

### ISSUE THREAD

**Issue by chelmerrox** [temesghentekeste/mint.com-signup-clone#2]
- good use of comments

- very clean code where there's less repetition of code

- good names for your classes in your  HTML

- smaller size for the text under the form

- use more classes than id's

- perhaps you should use the footer tag for the footer at the end of a web page rather than at the beginning or any where else within the main part of your code where you can use a section or a div instead.

**Comment by krys2fa** [comment]
Thanks for the recommendations. 

We have reduced the number of ids by implementing more classes now.

Also,  after some reading on w3schools, we found out that it is acceptable to have a number of header and footer tags in a document _provided they are used correctly_.
